# Generated by Django 2.1.4 on 2018-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualPDF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='parton',
            name='parton_num',
        ),
    ]
